### PR TITLE
:seedling: avoid to print whole event in the error log

### PR DESCRIPTION
**Pull request by skeeey**
## Summary
If the event is too large, it will cut off the error message in the log

### CODE REVIEW

**Comment by qiujian16** [comment]
if it is only event id, how is it valuable? Can we use it to find the specific event?

**Comment by skeeey** [comment]
> if it is only event id, how is it valuable? Can we use it to find the specific event?

Using event context instead of event id, the context will include the all event meta data, e.g. id, source, type, extensions etc.

**Pull request merged**
